---
#
# Copyright (c) 2016, PLUMgrid Inc, http://plumgrid.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install apt packages
  apt:
    name: jq
    state: latest
    force: yes
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: List all plugin files
  shell: "ls -1 {{ pg_source_plugin_dir }}{{ folder }}/*"
  register: plugin_files
  delegate_to: localhost

- name: Make plugin files executable
  file:
    path: "{{ item }}"
    mode: "0755"
  with_items: plugin_files.stdout_lines
  delegate_to: localhost

- name: Install PLUMgrid MAAS plugins
  synchronize:
    src: "{{ pg_source_plugin_dir }}{{ folder }}/"
    dest: "{{ maas_plugin_dir }}"

- name: List all checks files
  shell: "ls -1 {{ pg_source_check_dir }}{{ folder }}/*"
  register: checks_files
  delegate_to: localhost

- name: Install PLUMgrid MAAS checks
  template:
    src: "{{ item }}"
    dest: "/etc/rackspace-monitoring-agent.conf.d/{{ item | basename }}"
  with_items: checks_files.stdout_lines
