type        : agent.plugin
label       : "plumgrid_cdb_service_check--{{ ansible_hostname }}"
disabled    : false
period      : 60
timeout     : 30
details     :
    file    : check_pg_cdb.sh
alarms      :
    plumgrid_cdb_status :
        label                 : "plumgrid_cdb_status--{{ ansible_hostname }}"
        notification_plan_id  : "{{ maas_notification_plan }}"
        criteria              : |
            :set consecutiveCount={{ pg_alarm_consecutive_count }}
            if (metric["status_pg_cdb"] == "DOWN") {
              return new AlarmStatus(CRITICAL, "PLUMgrid Director[{{ ansible_hostname }}]: CDB service is down.");
            }
              return new AlarmStatus(OK, "PLUMgrid Director[{{ ansible_hostname }}]: CDB service is running.");
