type        : agent.plugin
label       : "plumgrid_keepalived_check--{{ ansible_hostname }}"
disabled    : false
period      : 60
timeout     : 30
details     :
    file    : check_pg_kalive.sh
alarms      :
    plumgrid_keepalived_status :
        label                 : "plumgrid_keepalived_status--{{ ansible_hostname }}"
        notification_plan_id  : "{{ maas_notification_plan }}"
        criteria              : |
            :set consecutiveCount={{ pg_alarm_consecutive_count }}
            if (metric["status_pg_kalive"] == "DOWN") {
              return new AlarmStatus(CRITICAL, "PLUMgrid Director[{{ ansible_hostname }}]: Keepalived service is down");
            }
              return new AlarmStatus(OK, "PLUMgrid Director[{{ ansible_hostname }}]: Keepalived service is running");
