type        : agent.plugin
label       : "plumgrid_sal_check--{{ ansible_hostname }}"
disabled    : false
period      : 60
timeout     : 30
details     :
    file    : check_pg_sal.sh
alarms      :
    plumgrid_sal_status :
        label                 : "plumgrid_sal_status--{{ ansible_hostname }}"
        notification_plan_id  : "{{ maas_notification_plan }}"
        criteria              : |
            :set consecutiveCount={{ pg_alarm_consecutive_count }}
            if (metric["status_pg_sal"] == "DOWN") {
              return new AlarmStatus(CRITICAL, "PLUMgrid Director[{{ ansible_hostname }}]: SAL is down");
            }
              return new AlarmStatus(OK, "PLUMgrid Director[{{ ansible_hostname }}]: SAL is up");
