type        : agent.plugin
label       : "plumgrid_service_directory_check--{{ ansible_hostname }}"
disabled    : false
period      : 60
timeout     : 30
details     :
    file    : check_pg_sd.sh
alarms      :
    plumgrid_service_directory_status :
        label                 : "plumgrid_service_directory_status--{{ ansible_hostname }}"
        notification_plan_id  : "{{ maas_notification_plan }}"
        criteria              : |
            :set consecutiveCount={{ pg_alarm_consecutive_count }}
            if (metric["status_pg_service_directory"] == "DOWN") {
              return new AlarmStatus(CRITICAL, "PLUMgrid Director[{{ ansible_hostname }}]: Service Directory is down");
            }
              return new AlarmStatus(OK, "PLUMgrid Director[{{ ansible_hostname }}]: Service Directory is running");
