type        : agent.plugin
label       : "plumgrid_system_manager_check--{{ ansible_hostname }}"
disabled    : false
period      : 60
timeout     : 30
details     :
    file    : check_pg_sm.sh
alarms      :
    plumgrid_system_manager_status :
        label                 : "plumgrid_system_manager_status--{{ ansible_hostname }}"
        notification_plan_id  : "{{ maas_notification_plan }}"
        criteria              : |
            :set consecutiveCount={{ pg_alarm_consecutive_count }}
            if (metric["status_pg_system_manager"] == "DOWN") {
              return new AlarmStatus(CRITICAL, "PLUMgrid Director[{{ ansible_hostname }}]: System Manager is down");
            }
              return new AlarmStatus(OK, "PLUMgrid Director[{{ ansible_hostname }}]: System Manager is running");
